# Generated by Django 3.2.3 on 2021-06-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
