# Generated by Django 3.2.3 on 2021-06-10 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_alter_company_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Профиль Компании', 'verbose_name_plural': 'Профили Компаний'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='response',
            options={'verbose_name': 'Отклик', 'verbose_name_plural': 'Отклики'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': 'Резюме', 'verbose_name_plural': 'Резюме'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Навык', 'verbose_name_plural': 'Навыки'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Профиль Студента', 'verbose_name_plural': 'Профили Студентов'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='company',
            name='photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='company',
            name='site_name',
            field=models.TextField(verbose_name='Cайт'),
        ),
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='companys', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Студент'), ('company', 'Компания'), ('admin', 'Админ')], default='student', max_length=50, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='response',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='main_site.resume', verbose_name='Резюме'),
        ),
        migrations.AlterField(
            model_name='response',
            name='status',
            field=models.CharField(choices=[(None, 'Не установлен'), ('student_response', 'Отклик студента'), ('offer', 'Предложение'), ('reject', 'Отказ'), ('offer_completed', 'Завершенный оффер')], default='published', max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='response',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='main_site.vacancy', verbose_name='Вакансия'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='about_self',
            field=models.TextField(verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='achievements',
            field=models.TextField(verbose_name='Достижения'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.TextField(verbose_name='Опыт'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='responsibilities',
            field=models.TextField(verbose_name='Обязанности'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.ManyToManyField(related_name='resumes', to='main_site.Skill', verbose_name='Навыки'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('blocked', 'Заблокированое'), ('closed', 'Закрытое'), ('published', 'Опубликованное')], default='published', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='main_site.student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='review',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main_site.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='mark',
            field=models.CharField(choices=[('excellent', 'Отлично'), ('good', 'Хорошо'), ('normal', 'Нормально'), ('bad', 'Плохо')], default='good', max_length=10, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main_site.student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='student',
            name='university_group',
            field=models.CharField(max_length=20, verbose_name='Группа в вузе'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancys', to='main_site.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='conditions',
            field=models.TextField(verbose_name='Условия'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=models.TextField(verbose_name='Требования'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='responsibilities',
            field=models.TextField(verbose_name='Обязанности'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='skills',
            field=models.ManyToManyField(related_name='vacancys', to='main_site.Skill', verbose_name='Навыки'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.CharField(choices=[('blocked', 'Заблокированая'), ('closed', 'Закрытая'), ('published', 'Опубликованная')], default='published', max_length=10, verbose_name='Статус'),
        ),
    ]
