# Generated by Django 3.2.3 on 2021-06-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0005_company_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='site_name',
            field=models.CharField(max_length=200, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='resumes', to='main_site.Skill', verbose_name='Навыки'),
        ),
        migrations.AlterField(
            model_name='review',
            name='mark',
            field=models.CharField(choices=[(None, 'Не установлен'), ('excellent', 'Отлично'), ('good', 'Хорошо'), ('normal', 'Нормально'), ('bad', 'Плохо')], default='good', max_length=10, verbose_name='Оценка'),
        ),
    ]
