# Generated by Django 3.2.3 on 2021-06-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0008_alter_response_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='document', verbose_name='Файл'),
        ),
    ]
